name: My First Workflow

on: push 

jobs:
     first_job:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             uses: actions/checkout@v4
           - name: List and Read the file
             run: |
               echo "My First GitHub Actions Job"
               ls -lrt
               cat README.md
           - name: Generate ASCII Network
             run: cowsay -f dragon "Run for cover, I AM a Dragon..." >>dragon.txt