name: My First Workflow

on: push 

jobs:
     first_job:
        runs-on: ubuntu-latest
        steps:
           - name: Welcome Message
             run: echo "My First Github ACtions Job"
           - name: List the files
             run: ls -lrt
           - name: Read the file
             run: cat README.md
