name: Generate ASCII Artwork

on:
    push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Chekout Repo
          uses: actions/checkout@v4
        - name: Install CowSay Program
          run: sudo apt-get install cowsay -y 
        - name: Execute shell script
          run: |
             chmod +x ascuu-script.sh 
             ./ascuu-script.sh
